
- name: Install docker os packages
  yum: pkg=docker-io-{{docker_version}} state=present

- name: Install pip
  yum: pkg=python-pip state=present

# Forcing this to 1.1.0 as latest version has incompatibilities. See https://github.com/ansible/ansible/issues/10879
- name: Install docker-py
  pip: name=docker-py version=1.1.0

- name: Docker init file
  template: src=docker-redhat.j2 dest=/etc/sysconfig/docker
  notify: Restart Docker

- name: Get Docker version
  shell: docker --version
  register: cmd_version
  changed_when: False

- name: Check Docker version
  assert:
    that:
      - "'{{docker_version}}' in cmd_version.stdout"

